package config

import (
	"McDailyAutoRun/common"
	"os"
)

var (
	// TCPPort ...
	TCPPort = "7404"
	// PprofPort ...
	PprofPort = "7405"
	// LineBotChannelSecret ...
	LineBotChannelSecret = os.Getenv("LINE_SECRET")
	// LineBotChannelToken ...
	LineBotChannelToken = os.Getenv("LINE_TOKEN")
	// User ...
	User = []common.User{}
	// AppVersion ...
	AppVersion = "2.2.0"
	// ModelID ...
	ModelID = "Pixel4 XL"
	// OsVersion ...
	OsVersion = "10"
	// DeviceUUID ...
	DeviceUUID = "device_uuid"
	// Platform ...
	Platform = "Android"
	// McDailyAPIHost ...
	McDailyAPIHost = "https://api.mcddaily.com.tw"
	// McDailyLoginURL ...
	McDailyLoginURL = McDailyAPIHost + "/login_by_mobile"
	// McDailyAPI1Host ...
	McDailyAPI1Host = "https://api1.mcddailyapp.com"
	// McDailyGetLottry ...
	McDailyGetLottry = McDailyAPI1Host + "/lottery/get_item"
	// McDailyGetLottryList ...
	McDailyGetLottryList = McDailyAPI1Host + "/coupon/get_list"
	// McDailyGetStickerList ...
	McDailyGetStickerList = McDailyAPI1Host + "/sticker/get_list"
)
